services:
  db:
    image: postgres:16
    container_name: jobtracker_db
    environment:
      POSTGRES_USER: jobtracker
      POSTGRES_PASSWORD: jobtracker
      POSTGRES_DB: jobtracker
    ports:
      - "5432:5432"
    volumes:
      - jobtracker_pg:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: jobtracker_redis
    ports:
      - "6379:6379"

volumes:
  jobtracker_pg:
